require("dotenv").config();
const express=require("express"),path=require("path"),crypto=require("crypto"),Database=require("better-sqlite3"),Razorpay=require("razorpay");
const app=express(),db=new Database("mm_living.db");db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT DEFAULT '',price INTEGER NOT NULL,mrp INTEGER NOT NULL,stock INTEGER DEFAULT 0,image TEXT DEFAULT '🛍️',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT DEFAULT '',address TEXT NOT NULL,city TEXT NOT NULL,state TEXT NOT NULL,pincode TEXT NOT NULL,amount INTEGER NOT NULL,payment_method TEXT NOT NULL,payment_status TEXT DEFAULT 'pending',order_status TEXT DEFAULT 'new',razorpay_order_id TEXT DEFAULT '',razorpay_payment_id TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,name TEXT,price INTEGER,qty INTEGER);`);
if(!db.prepare("SELECT COUNT(*) c FROM products").get().c){let s=db.prepare("INSERT INTO products(name,category,description,price,mrp,stock,image) VALUES(?,?,?,?,?,?,?)");[
["Square Plastic Planter Pot","Planters","Clean white planter.",299,399,25,"🪴"],["Multi-Purpose Kitchen Utility Set","Kitchen Utility","Everyday kitchen utility.",349,499,30,"🍳"],["Home Storage & Organiser Basket","Home Essentials","Useful storage basket.",399,549,20,"🧺"],["Minimal Home Decor Accent","Home Decor","Minimal home accent.",279,349,18,"🕯️"]].forEach(x=>s.run(...x))}
const rz=process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
app.use(express.json({limit:"1mb"}));const auth=(req,res,next)=>{let h=req.headers.authorization||"";if(!h.startsWith("Basic "))return res.set("WWW-Authenticate",'Basic realm="MM Living Admin"').sendStatus(401);let [u,p]=Buffer.from(h.slice(6),"base64").toString().split(":");if(u===process.env.ADMIN_USER&&p===process.env.ADMIN_PASSWORD)return next();res.set("WWW-Authenticate",'Basic realm="MM Living Admin"').sendStatus(401)};
const ono=()=>`MML-${Date.now().toString().slice(-8)}-${Math.floor(100+Math.random()*900)}`;
app.get("/api/products",(q,r)=>r.json(db.prepare("SELECT * FROM products WHERE active=1 ORDER BY id DESC").all()));
app.post("/api/orders",async(req,res)=>{try{let {customer,items,paymentMethod}=req.body;if(!customer?.name||!customer?.phone||!customer?.address||!customer?.city||!customer?.state||!customer?.pincode)return res.status(400).json({error:"Please fill required details"});if(!items?.length)return res.status(400).json({error:"Cart is empty"});let norm=[],sub=0;for(let i of items){let p=db.prepare("SELECT * FROM products WHERE id=? AND active=1").get(+i.productId),qty=Math.max(1,+i.qty||1);if(!p||qty>p.stock)return res.status(400).json({error:"Product unavailable or insufficient stock"});sub+=p.price*qty;norm.push({p,qty})}let total=sub+(sub>=499?0:49),no=ono();let tx=db.transaction(()=>{let x=db.prepare(`INSERT INTO orders(order_no,name,phone,email,address,city,state,pincode,amount,payment_method) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(no,customer.name,customer.phone,customer.email||"",customer.address,customer.city,customer.state,customer.pincode,total,paymentMethod);for(let x2 of norm){db.prepare("INSERT INTO order_items(order_id,product_id,name,price,qty) VALUES(?,?,?,?,?)").run(x.lastInsertRowid,x2.p.id,x2.p.name,x2.p.price,x2.qty);db.prepare("UPDATE products SET stock=stock-? WHERE id=?").run(x2.qty,x2.p.id)}return x.lastInsertRowid});let id=tx();if(paymentMethod==="razorpay"){if(!rz)return res.status(500).json({error:"Razorpay keys not configured"});let ro=await rz.orders.create({amount:total*100,currency:"INR",receipt:no});db.prepare("UPDATE orders SET razorpay_order_id=? WHERE id=?").run(ro.id,id);return res.json({orderNo:no,amount:total,keyId:process.env.RAZORPAY_KEY_ID,razorpayOrderId:ro.id})}db.prepare("UPDATE orders SET payment_status='cod',order_status='confirmed' WHERE id=?").run(id);res.json({orderNo:no,amount:total})}catch(e){console.error(e);res.status(500).json({error:"Order creation failed"})}});
app.post("/api/payment/verify",(req,res)=>{try{let {orderNo,razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body,o=db.prepare("SELECT * FROM orders WHERE order_no=?").get(orderNo);if(!o)return res.status(404).json({error:"Order not found"});let ex=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest("hex");if(ex!==razorpay_signature)return res.status(400).json({error:"Signature verification failed"});db.prepare("UPDATE orders SET payment_status='paid',order_status='confirmed',razorpay_payment_id=? WHERE id=?").run(razorpay_payment_id,o.id);res.json({ok:true})}catch(e){res.status(400).json({error:"Verification failed"})}});
app.post("/api/webhooks/razorpay",(req,res)=>{let sig=req.headers["x-razorpay-signature"];if(process.env.RAZORPAY_WEBHOOK_SECRET){let ex=crypto.createHmac("sha256",process.env.RAZORPAY_WEBHOOK_SECRET).update(JSON.stringify(req.body)).digest("hex");if(sig!==ex)return res.sendStatus(400)}let p=req.body.payload?.payment?.entity,o=db.prepare("SELECT id FROM orders WHERE razorpay_order_id=?").get(p?.order_id);if(o&&(req.body.event==="payment.captured"||req.body.event==="order.paid"))db.prepare("UPDATE orders SET payment_status='paid',order_status='confirmed',razorpay_payment_id=? WHERE id=?").run(p?.id||"",o.id);res.json({received:true})});
app.get("/api/admin/products",auth,(q,r)=>r.json(db.prepare("SELECT * FROM products ORDER BY id DESC").all()));
app.post("/api/admin/products",auth,(q,r)=>{let x=q.body,z=db.prepare("INSERT INTO products(name,category,description,price,mrp,stock,image) VALUES(?,?,?,?,?,?,?)").run(x.name,x.category,x.description||"",+x.price,+x.mrp,+x.stock||0,x.image||"🛍️");r.json({id:z.lastInsertRowid})});
app.put("/api/admin/products/:id",auth,(q,r)=>{let x=q.body;db.prepare("UPDATE products SET name=?,category=?,description=?,price=?,mrp=?,stock=?,image=?,active=? WHERE id=?").run(x.name,x.category,x.description||"",+x.price,+x.mrp,+x.stock||0,x.image||"🛍️",x.active?1:0,q.params.id);r.json({ok:true})});
app.delete("/api/admin/products/:id",auth,(q,r)=>{db.prepare("UPDATE products SET active=0 WHERE id=?").run(q.params.id);r.json({ok:true})});
app.get("/api/admin/orders",auth,(q,r)=>{let o=db.prepare("SELECT * FROM orders ORDER BY id DESC").all(),it=db.prepare("SELECT * FROM order_items").all(),m={};it.forEach(x=>(m[x.order_id]??=[]).push(x));r.json(o.map(x=>({...x,items:m[x.id]||[]})))});
app.put("/api/admin/orders/:id",auth,(q,r)=>{if(!["new","confirmed","packed","shipped","delivered","cancelled"].includes(q.body.status))return r.status(400).json({error:"Invalid status"});db.prepare("UPDATE orders SET order_status=? WHERE id=?").run(q.body.status,q.params.id);r.json({ok:true})});
app.use(express.static(path.join(__dirname,"public")));app.get("/admin",(q,r)=>r.sendFile(path.join(__dirname,"public/admin.html")));app.listen(process.env.PORT||3000,()=>console.log("MM Living running"));
